services:
  bag-backend:
    build: ./server
    env_file:
      - .env
    container_name: bag-backend
    restart: always
    expose:
      - "4001"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=4001
    # --- EL EXPLORADOR (HEALTHCHECK) ---
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/api/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s # 30 segundos de gracia para que Node y Mongo conecten
    networks:
      - proxy-network

  bag-frontend:
    build: ./client
    container_name: bag-frontend
    restart: always
    expose:
      - "80"
    # --- ESPERA AL BACKEND SANO ---
    depends_on:
      bag-backend:
        condition: service_healthy
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true